stages:
  - testing
  
before_script: . slack-notif-start.sh
after_script:
    - set -e
    - |
      if [ $CI_JOB_STATUS == 'success' ]; then
        . slack-notif-success.sh
      else
        . slack-notif-failed.sh
      fi
testing-realph:
  stage: testing
  rules:
    - if: '$TASKNAME == "realph"'
      when: always  
  script:
    - export PATH=/home/gitlab-runner/.nvm/versions/node/v18.12.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    - git fetch origin main
    - git checkout FETCH_HEAD
    - npm ci
    - npm run test
  tags:
    - realphtest
